contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #preprocessing channel"
    url: https://nfcore.slack.com/channels/preprocessing
    about: Discussion about the nf-core/preprocessing pipeline
